spring.application.name=ExpenseManagementSystem
server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/expensemanagementsystem
spring.datasource.username=madhu
spring.datasource.password=mitha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true